// Package complete answers the questions a shell cannot answer for itself.
//
// Every dynamic source here is a value someone would otherwise look up by
// running a command first: a bead id from bd ready, a tender from
// hugel tender --list, an entry id from hugel pile list. Those lookups are the
// whole cost of using hugel from a keyboard, and a shell is the right place to
// pay them.
//
// The knowledge lives in Go rather than in the completion script for two
// reasons. A shell function inside a generated heredoc cannot be tested, and
// the script should stay a thin caller so that adding a source never means
// regenerating what people have already installed.
package complete

// Source names a set of candidates. The dynamic ones are answered by
// hugel complete; the two file sources are left to the shell, which is better
// at paths than any program shelling out to find them.
type Source string

const (
	None     Source = ""
	Ready    Source = "ready"    // what a tender could start now
	Tended   Source = "tended"   // beads with a finished tender, for the gate
	Tenders  Source = "tenders"  // every tender the garden has started
	Live     Source = "live"     // tenders still working
	Spikes   Source = "spikes"   // tenders that explored rather than built
	Entries  Source = "entries"  // pile entry ids
	Beds     Source = "beds"     // projects the garden knows
	Sessions Source = "sessions" // transcript session ids
	Types    Source = "types"    // kinds of pile entry
	Branches Source = "branches" // git branches here
	Hooks    Source = "hooks"    // hooks hugel implements
	Dirs     Source = "dirs"     // shell-side: directories
)

// Dynamic reports whether a source is one hugel has to answer itself.
func (s Source) Dynamic() bool {
	switch s {
	case None, Dirs:
		return false
	}
	return true
}

// Flag is one option, as a completer needs it.
//
// Bool is not cosmetic: Go's flag package will not take a boolean's value from
// the following word, so offering an argument after --dry-run would complete
// something the program then ignores.
type Flag struct {
	Name string
	Desc string
	Bool bool
	Arg  Source
}

// Command is one hugel command. Args is what a positional argument means,
// which is the difference between completing a value of the right shape and
// completing the right value: hugel gate wants beads that have been tended,
// not every open bead.
type Command struct {
	Name  string
	Desc  string
	Args  Source
	Flags []Flag
	Subs  []Command
}

// Spec is every command hugel dispatches, and it is the only place the shape
// of the CLI is written down twice. spec_test.go walks the flag registrations
// in internal/cli and fails when the two disagree, because the last time this
// project had completions they were generated by cobra and died silently when
// cobra went. Drift that nothing notices is exactly how that happened.
var Spec = []Command{
	{Name: "yield", Desc: "what sessions cost, and how much was context", Flags: []Flag{
		{Name: "since", Desc: "only sessions ending within this window (30d, 2w, 48h)"},
		{Name: "all", Desc: "no time limit", Bool: true},
		{Name: "bed", Desc: "restrict to one bed", Arg: Beds},
		{Name: "sessions", Desc: "list sessions instead of beds", Bool: true},
		{Name: "session", Desc: "show one session in detail", Arg: Sessions},
		{Name: "limit", Desc: "rows to show in list views"},
		{Name: "soil", Desc: "report draws from the pile rather than spend", Bool: true},
		{Name: "changes", Desc: "report what each landed bead cost", Bool: true},
		{Name: "spikes", Desc: "report what each spike put in the pile", Bool: true},
		{Name: "json", Desc: "emit JSON", Bool: true},
		{Name: "root", Desc: "transcript root", Arg: Dirs},
	}},
	{Name: "digest", Desc: "distil a session into compostable material", Flags: []Flag{
		{Name: "session", Desc: "session id prefix", Arg: Sessions},
		{Name: "all", Desc: "report digest sizes across every session", Bool: true},
		{Name: "json", Desc: "emit the digest as JSON", Bool: true},
		{Name: "root", Desc: "transcript root", Arg: Dirs},
	}},
	{Name: "compost", Desc: "turn spent sessions into pile entries", Flags: []Flag{
		{Name: "session", Desc: "session id prefix", Arg: Sessions},
		{Name: "all", Desc: "compost every session", Bool: true},
		{Name: "dry-run", Desc: "show what would be written, write nothing", Bool: true},
		{Name: "bed", Desc: "restrict to one bed", Arg: Beds},
		{Name: "root", Desc: "transcript root", Arg: Dirs},
		{Name: "pile", Desc: "pile location", Arg: Dirs},
		{Name: "new", Desc: "only sessions whose transcript changed since the last run", Bool: true},
		{Name: "quiet", Desc: "write nothing to stdout", Bool: true},
	}},
	{Name: "pile", Desc: "the knowledge store", Subs: []Command{
		{Name: "init", Desc: "create the pile and its git repository"},
		{Name: "import", Desc: "take in legacy markdown entries", Args: Dirs},
		{Name: "list", Desc: "what the pile knows"},
		{Name: "show", Desc: "one entry in full", Args: Entries},
		{Name: "review", Desc: "record what you decided about an entry", Args: Entries},
	}, Flags: []Flag{
		{Name: "pile", Desc: "pile location", Arg: Dirs},
		{Name: "dry-run", Desc: "report what would be imported, write nothing", Bool: true},
		{Name: "bed", Desc: "restrict to one bed", Arg: Beds},
		{Name: "type", Desc: "restrict to one type", Arg: Types},
		{Name: "spike", Desc: "only what one spike found", Arg: Spikes},
		{Name: "limit", Desc: "rows to show"},
		{Name: "stats", Desc: "summarise instead of listing", Bool: true},
		{Name: "accept", Desc: "a human vouches for this entry", Bool: true},
		{Name: "reject", Desc: "this entry is wrong; keep it out of soil", Bool: true},
		{Name: "abandon", Desc: "what this entry describes was abandoned", Bool: true},
		{Name: "unreview", Desc: "take back a verdict; return it to unreviewed", Bool: true},
		{Name: "superseded-by", Desc: "id of the entry that replaced this one", Arg: Entries},
		{Name: "why", Desc: "the reason, recorded in the pile's git log"},
	}},
	{Name: "soil", Desc: "draw context from the pile", Flags: []Flag{
		{Name: "bed", Desc: "the bed the work is in", Arg: Beds},
		{Name: "type", Desc: "only this kind of knowledge", Arg: Types},
		{Name: "limit", Desc: "most entries to return"},
		{Name: "budget", Desc: "most tokens of soil to deliver"},
		{Name: "json", Desc: "emit JSON", Bool: true},
		{Name: "pile", Desc: "pile location", Arg: Dirs},
	}},
	{Name: "bed", Desc: "the projects the garden knows", Subs: []Command{
		{Name: "kin", Desc: "record that these names are one project", Args: Beds},
		{Name: "list", Desc: "every bed: where it lives and what work is open"},
	}, Flags: []Flag{
		{Name: "root", Desc: "transcript root", Arg: Dirs},
		{Name: "no-work", Desc: "skip reading bd; just say where beds live", Bool: true},
	}},
	{Name: "garden", Desc: "where the work is, across every bed", Flags: []Flag{
		{Name: "since", Desc: "how far back the knowledge side looks"},
		{Name: "limit", Desc: "most rows per bed and per group"},
		{Name: "root", Desc: "transcript root", Arg: Dirs},
		{Name: "pile", Desc: "pile location", Arg: Dirs},
	}},
	{Name: "tend", Desc: "judge what the garden did", Flags: []Flag{
		{Name: "since", Desc: "how far back to look (7d, 2w, 48h)"},
		{Name: "bed", Desc: "restrict the session counts to one bed", Arg: Beds},
		{Name: "root", Desc: "transcript root", Arg: Dirs},
		{Name: "pile", Desc: "pile location", Arg: Dirs},
		{Name: "limit", Desc: "most entries to show per group"},
	}},
	{Name: "tender", Desc: "work one bead, unattended, in tmux", Args: Ready, Flags: []Flag{
		{Name: "list", Desc: "what is being tended", Bool: true},
		{Name: "show", Desc: "print a tender's brief and result", Arg: Tenders},
		{Name: "stop", Desc: "end a tender", Arg: Live},
		{Name: "clean", Desc: "with --stop, remove the worktree too", Bool: true},
		{Name: "ask-permission", Desc: "let the agent stop and ask", Bool: true},
		{Name: "attach", Desc: "a person will sit in the pane", Bool: true},
		{Name: "note", Desc: "anything else this tender should know"},
		{Name: "root", Desc: "transcript root", Arg: Dirs},
		{Name: "soil", Desc: "tokens of soil to put in the brief; 0 for none"},
	}},
	{Name: "spike", Desc: "explore a question; records findings, writes no code", Args: Ready, Flags: []Flag{
		{Name: "attach", Desc: "a person will sit in the pane", Bool: true},
		{Name: "ask-permission", Desc: "let the agent stop and ask", Bool: true},
		{Name: "note", Desc: "anything else this spike should know"},
		{Name: "root", Desc: "transcript root", Arg: Dirs},
		{Name: "soil", Desc: "tokens of soil to put in the brief; 0 for none"},
	}},
	{Name: "gate", Desc: "test, review, test again, then land it", Args: Tended, Flags: []Flag{
		{Name: "into", Desc: "branch the work lands on", Arg: Branches},
		{Name: "remote", Desc: "remote to push to; empty pushes nothing"},
		{Name: "test", Desc: "test command (default: discovered from the project)"},
		{Name: "wait", Desc: "how long to give the reviewer"},
		{Name: "dry-run", Desc: "stop before anything irreversible", Bool: true},
		{Name: "ask-permission", Desc: "let the reviewer stop and ask", Bool: true},
		{Name: "v", Desc: "print each stage's output", Bool: true},
		{Name: "grade", Desc: "report the survival rate of approved work", Bool: true},
		{Name: "since", Desc: "with --grade, landings within this window"},
		{Name: "mature", Desc: "with --grade, how long a landing must stand"},
		{Name: "bed", Desc: "with --grade, restrict to one bed", Arg: Beds},
		{Name: "json", Desc: "with --grade, emit JSON", Bool: true},
	}},
	{Name: "dispatch", Desc: "fill the tender slots from the ready queue", Flags: []Flag{
		{Name: "slots", Desc: "how many tenders may be working at once"},
		{Name: "bed", Desc: "only dispatch work in this bed", Arg: Beds},
		{Name: "dry-run", Desc: "say what would be started", Bool: true},
		{Name: "soil", Desc: "tokens of soil in each brief"},
		{Name: "ask-permission", Desc: "let tenders stop and ask", Bool: true},
		{Name: "root", Desc: "transcript root", Arg: Dirs},
	}},
	{Name: "hooks", Desc: "what the harness runs on hugel's behalf", Args: Hooks},
	{Name: "complete", Desc: "candidates for a shell completion", Args: None},
	{Name: "completion", Desc: "emit a completion script"},
}

// Find returns a command by name.
func Find(name string) (Command, bool) {
	for _, c := range Spec {
		if c.Name == name {
			return c, true
		}
	}
	return Command{}, false
}
