package complete

import (
	"fmt"
	"strings"
)

// Zsh renders a completion script for the whole CLI.
//
// Generated rather than checked in. A static _hugel drifts the moment a flag
// is added, and drifts silently -- which is how this project lost completions
// the first time, when the generation that had them stopped using the library
// that produced them. A script emitted by the binary cannot describe a flag
// the binary does not have.
//
// It stays thin on purpose. Every list that changes as work happens is fetched
// by calling hugel complete, so a script installed today keeps working when a
// source is added tomorrow. What is baked in is only the shape of the CLI,
// which changes when the binary does.
func Zsh() string {
	var b strings.Builder
	b.WriteString(`#compdef hugel
#
# zsh completion for hugel, generated by `)
	b.WriteString("`hugel completion zsh`")
	b.WriteString(`. Do not edit: regenerate.
#
# Anything that changes as work happens -- beads, tenders, pile entries -- is
# asked of the binary at completion time through `)
	b.WriteString("`hugel complete`")
	b.WriteString(`.

_hugel_dyn() {
  local -a items
  items=(${(f)"$(hugel complete $1 2>/dev/null)"})
  (( ${#items} )) || return 1
  _describe -t "$1" "$1" items
}

`)

	for _, c := range Spec {
		if c.Name == "complete" || c.Name == "completion" {
			continue
		}
		b.WriteString(commandFunc(c))
	}
	b.WriteString(completionFunc())

	b.WriteString("_hugel() {\n")
	b.WriteString("  local curcontext=\"$curcontext\" state line ret=1\n")
	b.WriteString("  typeset -A opt_args\n\n")
	b.WriteString("  _arguments -C '1: :->command' '*:: :->args' && ret=0\n\n")
	b.WriteString("  case $state in\n")
	b.WriteString("    command)\n")
	b.WriteString("      local -a cmds\n")
	b.WriteString("      cmds=(\n")
	for _, c := range Spec {
		b.WriteString("        " + quote(c.Name+":"+escapeDesc(c.Desc)) + "\n")
	}
	b.WriteString("      )\n")
	b.WriteString("      _describe -t commands 'hugel command' cmds && ret=0\n")
	b.WriteString("      ;;\n")
	b.WriteString("    args)\n")
	b.WriteString("      case $words[1] in\n")
	for _, c := range Spec {
		if c.Name == "complete" {
			b.WriteString("        complete) _hugel_dyn_sources && ret=0 ;;\n")
			continue
		}
		b.WriteString(fmt.Sprintf("        %s) _hugel_%s && ret=0 ;;\n", c.Name, fnName(c.Name)))
	}
	b.WriteString("      esac\n")
	b.WriteString("      ;;\n")
	b.WriteString("  esac\n")
	b.WriteString("  return ret\n")
	b.WriteString("}\n\n")

	b.WriteString("_hugel_dyn_sources() {\n")
	b.WriteString("  local -a s\n  s=(\n")
	for _, s := range Sources() {
		b.WriteString("    " + quote(s) + "\n")
	}
	b.WriteString("  )\n  _describe -t sources source s\n}\n\n")

	b.WriteString("_hugel \"$@\"\n")
	return b.String()
}

// commandFunc renders one command's completer.
func commandFunc(c Command) string {
	var b strings.Builder
	fmt.Fprintf(&b, "_hugel_%s() {\n", fnName(c.Name))
	if len(c.Subs) == 0 {
		b.WriteString("  _arguments \\\n")
		for _, f := range c.Flags {
			b.WriteString("    " + quote(flagSpec(f)) + " \\\n")
		}
		b.WriteString("    " + quote(argSpec(c.Args, "*")) + "\n")
		b.WriteString("}\n\n")
		return b.String()
	}

	b.WriteString("  local curcontext=\"$curcontext\" state line\n")
	b.WriteString("  _arguments -C \\\n")
	for _, f := range c.Flags {
		b.WriteString("    " + quote(flagSpec(f)) + " \\\n")
	}
	b.WriteString("    '1: :->sub' \\\n    '*:: :->rest'\n\n")
	b.WriteString("  case $state in\n")
	b.WriteString("    sub)\n      local -a subs\n      subs=(\n")
	for _, s := range c.Subs {
		b.WriteString("        " + quote(s.Name+":"+escapeDesc(s.Desc)) + "\n")
	}
	fmt.Fprintf(&b, "      )\n      _describe -t subcommands '%s subcommand' subs\n      ;;\n", c.Name)
	b.WriteString("    rest)\n      case $words[1] in\n")
	for _, s := range c.Subs {
		b.WriteString(fmt.Sprintf("        %s) _arguments \\\n", s.Name))
		for _, f := range c.Flags {
			b.WriteString("          " + quote(flagSpec(f)) + " \\\n")
		}
		b.WriteString("          " + quote(argSpec(s.Args, "*")) + " ;;\n")
	}
	b.WriteString("      esac\n      ;;\n  esac\n}\n\n")
	return b.String()
}

func completionFunc() string {
	return `_hugel_completion() {
  local -a shells
  shells=('zsh:a script for zsh')
  _describe -t shells shell shells
}

`
}

// flagSpec renders one option for _arguments.
//
// A boolean takes no argument, and saying otherwise would be a lie the shell
// repeats: Go's flag package will not read a bool's value from the next word,
// so a completed value would be silently dropped.
func flagSpec(f Flag) string {
	if f.Bool {
		return "--" + f.Name + "[" + escapeDesc(f.Desc) + "]"
	}
	return "--" + f.Name + "=[" + escapeDesc(f.Desc) + "]" + argSpec(f.Arg, "")
}

// argSpec renders the ":message:action" half of a spec.
func argSpec(s Source, pos string) string {
	msg := string(s)
	if msg == "" {
		msg = "value"
	}
	switch s {
	case None:
		return pos + ":" + msg + ":"
	case Dirs:
		return pos + ":directory:_files -/"
	default:
		// Braced, because a bare "_hugel_dyn ready" is read by _arguments as
		// an action word rather than a command with an argument, and silently
		// completes nothing -- which is indistinguishable from having no
		// completion at all. The braces make it shell code, which runs.
		return pos + ":" + msg + ":{_hugel_dyn " + string(s) + "}"
	}
}

func fnName(s string) string { return strings.ReplaceAll(s, "-", "_") }

// escapeDesc protects the characters _arguments reads as structure. A colon
// ends a description and a bracket ends the option, so "with --grade: restrict
// to one bed" would otherwise truncate at the colon.
func escapeDesc(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `[`, `\[`, `]`, `\]`, `:`, `\:`)
	return r.Replace(s)
}

// quote wraps a word in single quotes, which is the only quoting zsh does not
// interpret further -- descriptions here contain apostrophes.
func quote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
